### PR TITLE
Update and rename README.mkd to README.md

### PR DESCRIPTION
**Pull request by ghost**
Fixes #https://github.com/publiclab/plots2/issues/3699

r? @jywarren @sagarpreet-chadha @SidharthBansal @publiclab/mentors

### CODE REVIEW

**Review by SidharthBansal — APPROVED** [review]
Great

**Review by Rishabh570 — APPROVED** [review]
Looks nice :+1: 
Thanks for your contribution :tada:

**Review by grvsachdeva — APPROVED** [review]

**Comment by jywarren** [comment]
Hi, this is great! I'll merge this now. Thanks a lot!!!

**Comment by jywarren** [comment]
🎉

**Pull request merged**
