### PR TITLE
Updated bootstrap.css

### PR DESCRIPTION
**Pull request by DakshGondaliya**
Fixes: publiclab/plots2#3636

### CODE REVIEW

**Comment by DakshGondaliya** [comment]
@jywarren please review it.

**Comment by avsingh999** [comment]
@DakshGondaliya  thank you for contribution
can you please post a gif/Screenpost. It would be better for us to understanding what you have done
thanks

**Comment by DakshGondaliya** [comment]
@avsingh999 please go through https://github.com/publiclab/plots2/issues/3636, I already uploaded screenshot and video of the improved look there.
Thank you.

**Comment by DivyeshPuri** [comment]
@DakshGondaliya You have made the changes in bootstrap.css which might bring changes to other sections as well and if not now then in future this might affect our project. I will suggest you to either make the following CSS changes inline or by writing the same in a different CSS file.

**Review by DivyeshPuri — CHANGES_REQUESTED** [review]
@DakshGondaliya You have made the changes in bootstrap.css which might bring changes to other sections as well and if not now then in future this might affect our project. I will suggest you to either make the following CSS changes inline or by writing the same in a different CSS file.

**Comment by DakshGondaliya** [comment]
@DivyeshPuri inline CSS require lots of work as I applied changes to all blocks of images and moreover, I only added some properties to already existing class in bootstrap.css, so I think It does not require a different CSS file.
Thank you.🙂

**Comment by DivyeshPuri** [comment]
@DakshGondaliya Inlining CSS won't require much work as images are being rendered dynamically. Also, I am saying that it is not a good practice to make changes in front-end frameworks as they might create problems in the future.

**Comment by DakshGondaliya** [comment]
@DivyeshPuri Thank you for guiding.

**Pull request closed without merging**
