### PR TITLE
Updated infragram.css

### LINKED ISSUE #3636: Improve the look of Infragram
### Please describe the problem (or idea)
Change the look of the block of images and pagination.
> What happened just before the problem occurred? Or what problem could this idea solve?
### Screenshot 1
currentview1

### Screenshot 2
currentview2

### Screenshot 3
currentview3

> What did you expect to see that you didn't?
### Video of the Improved look
[ImprovedLook.zip](https://github.com/publiclab/plots2/files/2453006/ImprovedLook.zip)

### Screenshot 1
newview3

### Screenshot 2
newview1

### Screenshot 3
newview2

### Please show us where to look
http://infragram.org

### What's your PublicLab.org username?
dynamic_daksh
> This can help us diagnose the issue: 

### Browser, version, and operating system
Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit), Windows 10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by DakshGondaliya**
Fixes: publiclab/plots2#3636
Screenshots and video of improved look added at publiclab/plots2#3636

### CODE REVIEW

**Comment by DakshGondaliya** [comment]
@jywarren please review it.

**Comment by jywarren** [comment]
Oh, this is really nice! Thank you! Would you mind rebasing over the latest main branch? Actually we have started using the `main` branch instead of the `master` branch here, so if you were able to post a new PR against that branch that would be great. 

Also, I would love to see a screenshot of your changes! 

Again, thanks so much!

**Comment by jywarren** [comment]
Oh, i see you posted screenshots already. Great.

**Comment by jywarren** [comment]
Perhaps another 8 pixels of padding inside each picture frame would be nice! And does each photo need the rounded-edged frame as well? 

I appreciate your work on this!

**Comment by jywarren** [comment]
You know, I am wondering if the extra shadow and frame is really necessary. I love that you are thinking hard about this, and was curious if you would like to try formatting the date to be shorter, so it looks less busy. I think that shortening or formatting the date would potentially do more to help format this than the drop shadow styles. Would you mind reverting the drop shadow and attempting to edit the date format? 

I also love the edits you've made to the setup instructions. Thanks so much!

**Comment by grvsachdeva** [comment]
Hi @DakshGondaliya, do you need any help with this PR? Thanks!

**Comment by grvsachdeva** [comment]
Also, there are many changes in views of https://infragram.org. Thanks!

**Pull request closed without merging**
