### PR TITLE
Edited the line as mentioned!

### PR DESCRIPTION
**Pull request by ritikgupta4**
Thanks for the help!

### CODE REVIEW

**Comment by Rishabh570** [comment]
@ritikgupta4 Great! Thanks for your contribution!!!
BTW referencing the related issue in PR description helps people know about any existing PR for that issue, saves from any confusion. You can do that by writing `Fixes #{issue_number}` in the PR description...
Thanks!

**Review by Rishabh570 — APPROVED** [review]
:+1:

**Comment by ritikgupta4** [comment]
Duly noted! Thanks!

**Comment by Rishabh570** [comment]
@jywarren Ready-to-merge!

**Comment by jywarren** [comment]
Thanks!!!!

**Pull request merged**
