### PR TITLE
Improve pagination buttons

### PR DESCRIPTION
**Pull request by faithngetich**
Issue [link](https://github.com/publiclab/plots2/issues/3652#issuecomment-429194073)

GIF link
---------
http://g.recordit.co/vZRm1bMq36.gif
 
screen shot 2018-10-17 at 11 37 40
screen shot 2018-10-17 at 11 39 25

### CODE REVIEW

**Comment by faithngetich** [comment]
Hey, @publiclab/reviewers Kindly review this PR. 
Thank-you.

**Comment by avsingh999** [comment]
@faithngetich  great, please add a screenshot/Gif 
thanks :)

**Comment by faithngetich** [comment]
http://g.recordit.co/vZRm1bMq36.gif

@avsingh999 I used a different software to create it. The recommended software for some reason is not working for me.  Also below is a screenshot 
screen shot 2018-10-17 at 11 37 40
screen shot 2018-10-17 at 11 39 25

**Comment by faithngetich** [comment]
Hey, @jywarren could you please review this PR.

**Comment by avsingh999** [comment]
@jywarren it looks good to me ,please review 
thank you :)

**Review by Rishabh570 — APPROVED** [review]
Great work :tada: 
@jywarren Please take a look :)

**Review by avsingh999 — APPROVED** [review]

**Review by Rishabh-Kumar-Bothra — APPROVED** [review]

**Comment by jywarren** [comment]
Awesome, thank you!!!

**Pull request merged**
